import exception from "./exception";

const argv = process.argv.slice(2, 4);

exception(argv);
